### ISSUE TITLE
multimodule

### ISSUE THREAD

**Issue by gunslingor** [skubicz/maven-executor-plugin#3]
Hello,

The plugin doesn't seem to work with 3 layers of modules, only the first 2 layers are shown in the tree. Main reason I was using this plugin was for the tree interface... much better than the default... but if it won't show the entire tree it wouldn't work for me. Perhaps this is by design for some reason?

**Comment by skubicz** [comment]
Hi,

Do you mean the number of nests in the tree graph?
There are no limitation, for example:
![image](https://user-images.githubusercontent.com/3798300/121582181-01f46680-ca2f-11eb-8081-c52234c83c95.png)

Maybe you have wrong POM maven definition (in parent or modules sections).

**Comment by gunslingor** [comment]
Ah, okay, i see... it works now... I think intellij was ignoring the lower modules. Pretty cool plugin, better than the default!
